### PR TITLE
Bump version, label fix from ben-st

### PR DESCRIPTION
**Pull request by ironsalsa**
Adding in PR from ben-st, with the version bump to 3.8.0 so we can merge this request.

### CODE REVIEW

**Comment by ironsalsa** [comment]
Just so you know, I've tested these changes on my own, and actually applied them to my production environments without incident thus far.

**Comment by cavemandaveman** [comment]
My tests confirm the same, updating shouldn't be an issue. Thank you!

**Comment by utf18** [comment]
yeah lgtm :)

**Comment by bcg62** [comment]
can you push these new tags to docker hub as well? https://hub.docker.com/r/clearent/nexus/

**Comment by cavemandaveman** [comment]
@bcg62 That repo is deprecated. Please use https://hub.docker.com/r/cavemandaveman/nexus/ if you want the latest updates.

**Pull request merged**
